server: 
  port: 8081
spring: 
  datasource: 
    password: Admin.1234
    url: "jdbc:sqlserver://192.168.85.191:1433;databaseName=NAVISION"
    username: SA
  jpa: 
    database-platform: org.hibernate.dialect.SQLServer2012Dialect